#!/bin/bash

# Claude Changelog Generator
# Automatically generates a structured CHANGELOG.md from git history

# Exit on any error
set -e

# Configuration
CHANGELOG_FILE="CHANGELOG.md"
TEMP_COMMIT_LIST=$(mktemp)
TEMP_TAG_LIST=$(mktemp)

# Cleanup function
cleanup() {
    rm -f "$TEMP_COMMIT_LIST" "$TEMP_TAG_LIST"
}
trap cleanup EXIT

# Get the latest tag or default to initial commit
latest_tag=$(git describe --tags --abbrev=0 2>/dev/null) || latest_tag=$(git rev-list --max-parents=0 HEAD)

# Get commit range
if [ -n "$latest_tag" ] && [ "$latest_tag" != "$(git rev-list --max-parents=0 HEAD)" ]; then
    # There's a previous tag, so get commits since that tag
    git log --oneline "$latest_tag"..HEAD > "$TEMP_COMMIT_LIST"
else
    # No previous tag, get all commits
    git log --oneline > "$TEMP_COMMIT_LIST"
fi

# Generate CHANGELOG.md
{
    echo "# Changelog"
    echo "All notable changes to this project will be documented in this file."
    echo
    if [ -n "$latest_tag" ] && [ "$latest_tag" != "$(git rev-list --max-parents=0 HEAD)" ]; then
        echo "## [$(git describe --tags --abbrev=0)] - $(git log -1 --format='%ad' --date=short)"
    else
        echo "## [Unreleased]"
    fi
    echo

    # Check if there are any Added commits
    if grep -q "^.*feat:.*" "$TEMP_COMMIT_LIST"; then
        echo "### Added"
        echo
        grep "^.*feat:.*" "$TEMP_COMMIT_LIST" | while read -r line; do
            echo "- $(echo "$line" | sed 's/^[0-9a-f]* feat: //g')"
        done
        echo
    fi

    # Check if there are any Fixed commits
    if grep -q "^.*fix:.*" "$TEMP_COMMIT_LIST"; then
        echo "### Fixed"
        echo
        grep "^.*fix:.*" "$TEMP_COMMIT_LIST" | while read -r line; do
            echo "- $(echo "$line" | sed 's/^[0-9a-f]* fix: //g')"
        done
        echo
    fi

    # Check if there are any Changed commits
    if grep -q "^.*chore:.*\|^.*refactor:.*\|^.*docs:.*\|^.*style:.*\|^.*test:.*" "$TEMP_COMMIT_LIST"; then
        echo "### Changed"
        echo
        grep "^.*chore:.*\|^.*refactor:.*\|^.*docs:.*\|^.*style:.*\|^.*test:.*" "$TEMP_COMMIT_LIST" | while read -r line; do
            echo "- $(echo "$line" | sed 's/^[0-9a-f]* [chore|refactor|docs|style|test]*: //g')"
        done
        echo
    fi

    # Check if there are any Removed commits
    if grep -q "^.*remove:.*" "$TEMP_COMMIT_LIST"; then
        echo "### Removed"
        echo
        grep "^.*remove:.*" "$TEMP_COMMIT_LIST" | while read -r line; do
            echo "- $(echo "$line" | sed 's/^[0-9a-f]* remove: //g')"
        done
        echo
    fi

    echo "[Comment]: # (This file is auto-generated by changelog.sh)"
} > "$CHANGELOG_FILE"

echo "✅ Generated CHANGELOG.md"