#!/usr/bin/env bash

# changelog.sh - Generate a structured CHANGELOG.md from git history
# Usage: bash changelog.sh

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Get the last git tag
get_last_tag() {
    git describe --tags --abbrev=0 2>/dev/null || echo ""
}

# Get commits since the last tag (or all commits if no tag)
get_commits() {
    local last_tag="$1"
    if [ -n "$last_tag" ]; then
        git log "${last_tag}..HEAD" --pretty=format:"%s" 2>/dev/null || echo ""
    else
        git log --pretty=format:"%s" 2>/dev/null || echo ""
    fi
}

# Categorize a single commit message
categorize_commit() {
    local msg="$1"
    local lower_msg
    lower_msg=$(echo "$msg" | tr '[:upper:]' '[:lower:]')
    
    # Check for conventional commit prefixes first
    if [[ "$lower_msg" =~ ^feat(\(.+\))?: ]]; then
        echo "added"
    elif [[ "$lower_msg" =~ ^fix(\(.+\))?: ]]; then
        echo "fixed"
    elif [[ "$lower_msg" =~ ^(chore|refactor|perf|style)(\(.+\))?: ]]; then
        echo "changed"
    elif [[ "$lower_msg" =~ ^(remove|delete|drop)(\(.+\))?: ]]; then
        echo "removed"
    else
        # Fallback: keyword-based categorization
        if [[ "$lower_msg" =~ ^(add|create|introduce|implement|new) ]]; then
            echo "added"
        elif [[ "$lower_msg" =~ ^(fix|resolve|patch|bugfix|hotfix|correct) ]]; then
            echo "fixed"
        elif [[ "$lower_msg" =~ ^(remove|delete|drop|eliminate|clean) ]]; then
            echo "removed"
        else
            echo "changed"
        fi
    fi
}

# Generate the CHANGELOG.md
generate_changelog() {
    local last_tag
    last_tag=$(get_last_tag)
    
    echo -e "${YELLOW}📋 Generating CHANGELOG...${NC}"
    
    if [ -n "$last_tag" ]; then
        echo -e "${GREEN}Last tag found: $last_tag${NC}"
    else
        echo -e "${YELLOW}No tags found. Using all commits.${NC}"
    fi
    
    local commits
    commits=$(get_commits "$last_tag")
    
    if [ -z "$commits" ]; then
        echo -e "${RED}No commits found since last tag.${NC}"
        exit 0
    fi
    
    # Initialize category arrays
    local added=()
    local fixed=()
    local changed=()
    local removed=()
    
    # Process each commit
    while IFS= read -r commit; do
        [ -z "$commit" ] && continue
        
        local category
        category=$(categorize_commit "$commit")
        
        case "$category" in
            added)   added+=("$commit") ;;
            fixed)   fixed+=("$commit") ;;
            removed) removed+=("$commit") ;;
            changed) changed+=("$commit") ;;
        esac
    done <<< "$commits"
    
    # Get the date
    local date_str
    date_str=$(date +%Y-%m-%d)
    
    # Get version for header
    local version
    if [ -n "$last_tag" ]; then
        version="$last_tag → HEAD"
    else
        version="HEAD"
    fi
    
    # Generate CHANGELOG.md
    {
        echo "# Changelog"
        echo ""
        echo "## [Unreleased] - $date_str"
        echo ""
        
        if [ ${#added[@]} -gt 0 ]; then
            echo "### Added"
            for item in "${added[@]}"; do
                echo "- $item"
            done
            echo ""
        fi
        
        if [ ${#fixed[@]} -gt 0 ]; then
            echo "### Fixed"
            for item in "${fixed[@]}"; do
                echo "- $item"
            done
            echo ""
        fi
        
        if [ ${#changed[@]} -gt 0 ]; then
            echo "### Changed"
            for item in "${changed[@]}"; do
                echo "- $item"
            done
            echo ""
        fi
        
        if [ ${#removed[@]} -gt 0 ]; then
            echo "### Removed"
            for item in "${removed[@]}"; do
                echo "- $item"
            done
            echo ""
        fi
        
        echo "---"
        echo ""
        echo "*Generated by changelog.sh*"
    } > CHANGELOG.md
    
    echo -e "${GREEN}✅ CHANGELOG.md generated successfully!${NC}"
}

# Main execution
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo -e "${RED}Error: Not a git repository.${NC}"
    exit 1
fi

generate_changelog
# /generate-changelog

Generate a structured `CHANGELOG.md` from a project's git history.

## Description

This skill fetches commits since the last git tag, auto-categorizes them into
`Added`, `Fixed`, `Changed`, and `Removed`, and outputs a properly formatted
`CHANGELOG.md`.

## Usage

Run the following command in your terminal:

