#!/bin/bash

# changelog.sh - Generate a structured CHANGELOG.md from git history
#
# This script fetches commits since the last git tag and auto-categorizes them
# into Added, Fixed, Changed, and Removed sections.
#
# Usage:
#   ./changelog.sh
#
# Requirements:
#   - Git

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_color() {
    color=$1
    message=$2
    echo -e "${color}${message}${NC}"
}

# Check if we're in a git repository
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    print_color $RED "Error: Not in a git repository"
    exit 1
fi

# Get the latest tag or use initial commit if no tags exist
LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || git rev-list --max-parents=0 HEAD)

if [ -z "$LATEST_TAG" ]; then
    print_color $RED "Error: No commits found"
    exit 1
fi

print_color $BLUE "Generating changelog since tag: $LATEST_TAG"

# Get commits since the last tag (excluding merge commits)
COMMITS=$(git log --no-merges --pretty=format:"%s" $LATEST_TAG..HEAD 2>/dev/null || true)

# If no commits since last tag, exit gracefully
if [ -z "$COMMITS" ]; then
    print_color $YELLOW "No commits since last tag. Changelog unchanged."
    exit 0
fi

# Initialize arrays for each category
declare -a ADDED COMMITS
declare -a FIXED COMMITS
declare -a CHANGED COMMITS
declare -a REMOVED COMMITS

# Categorize commits based on keywords in the subject line
while IFS= read -r commit; do
    case "$commit" in
        *[Aa]dd*|*[Ff]eature*|*[Nn]ew*)
            ADDED+=("$commit")
            ;;
        *[Ff]ix*|*[Bb]ug*|*[Rr]esolve*)
            FIXED+=("$commit")
            ;;
        *[Cc]hange*|*[Uu]pdate*|*[Mm]odify*)
            CHANGED+=("$commit")
            ;;
        *[Rr]emove*|*[Dd]elete*|*[Rr]m*)
            REMOVED+=("$commit")
            ;;
        *)
            # Default to Added if no keywords match
            ADDED+=("$commit")
            ;;
    esac
done <<< "$COMMITS"

# Generate the changelog content
{
    echo "# Changelog"
    echo ""
    echo "All notable changes to this project will be documented in this file."
    echo ""
    echo "The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),"
    echo "and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html)."
    echo ""
    echo "## [Unreleased]"
    echo ""
    
    # Function to print section
    print_section() {
        local section_name=$1
        local commits_array=("${!2}")
        if [ ${#commits_array[@]} -gt 0 ]; then
            echo "### $section_name"
            for commit in "${commits_array[@]}"; do
                echo "- $commit"
            done
            echo ""
        fi
    }
    
    print_section "Added" ADDED[@]
    print_section "Fixed" FIXED[@]
    print_section "Changed" CHANGED[@]
    print_section "Removed" REMOVED[@]
    
    echo "[//]: # (Generated by changelog.sh script)"
} > CHANGELOG.md

print_color $GREEN "Changelog successfully generated in CHANGELOG.md"